### ISSUE TITLE
Idee - Gesamtstatistiken

### ISSUE THREAD

**Issue by circlecubee** [Hyperjo/Dokumentation#1]
Meine Idee ist es, die Gesamtstatistik einzuführen, welche dann z.B folgendes beinhaltet:

- Aktuelles Geld im Umlauf (von allen Spielern)
- Anzahl, Name und Kategorien der gekauften Fahrzeuge in der letzten Zeit (von allen Spielern)

**Comment by Markus1812** [comment]
Hey @circlecubee,

wir haben gestern zwei Neuerungen eingefügt, mit denen du deine Ideen ziemlich gut umsetzen können solltest. Eine direkte Übersicht aller in letzter Zeit verkaufter Fahrzeuge können wir leider so nicht umsetzen, da daraus Rückschlüsse auf das aktuelle Verhalten von Spielern auf dem Server gezogen werden können.

### Neue Funktion: `globalstats`
Liefert einige globale Statistiken wie Anzahl der erstellten Charaktere, Anzahl der Fahrzeuge, gesamtes Geld und Spielzeit. Mehr Infos hier:
https://github.com/Hyperjo/Dokumentation/blob/main/documentation/globalstats.md

### Geänderte Funktion: `vehicles`
Außerdem haben wir das Kaufdatum und die gefahrenen Meter in die `vehicles` Funktion eingefügt. Damit kann man zumindest von angemeldeten Spielern eine Statistik über Fahrzeugkäufe erstellen.
https://github.com/Hyperjo/Dokumentation/blob/main/documentation/vehicles.md
