### ISSUE TITLE
Idee - Gangstatistiken

### ISSUE THREAD

**Issue by Distel04** [Hyperjo/Dokumentation#2]
Meine Idee wäre eine Übersicht mit Gangstatistiken, wo man folgendes sehen kann:

-Anzahl aller Gangs 
-Anzahl aller Ganghäuser
-Anzahl aller Gangfahrzeuge
-Anzahl von Chars, welche in einer Gang sind
-Bankvermögen aller Gangs

**Comment by Markus1812** [comment]
Hey Distel,

wir haben die gewünschten Statistiken in unsere API eingefügt und in der Dokumentation beschrieben. Hier findest du weitere Informationen dazu:
https://github.com/Hyperjo/Dokumentation/blob/294f4f4d4808150e2ca8e27780c4b5d97ea75bbf/documentation/globalgangstats.md
