### ISSUE TITLE
Änderung - FarmingPreise Item über Array Key

### ISSUE THREAD

**Issue by Distel04** [Hyperjo/Dokumentation#3]
Ich hatte eine Idee zu einer Änderung. Mir ist beim programmieren aufgefallen, dass es sehr schnell unübersichtlich wird, wenn man mit den FarmingPreisen arbeitet, weil man nicht weiß, bei welchem Item man gerade ist, weil normale Keys verwendet wurden.

Aktueller Aufruf sieht so aus: farmingObject[3]["price"];

Neuer Aufruf: farmingObject["Meth"]["price"];

Dadurch wüsste man direkt, an welchem Item man gerade arbeitet und es wäre übersichtlicher.

**Comment by Markus1812** [comment]
Hey Distel,

tatsächlich haben wir hier eine Liste im JSON-Objekt gewählt, weil unsere interne Repräsentation der Farmingpreise in einer Liste ist. Deshalb wäre es für uns ungünstig, dies in der API zu einem Objekt zu ändern. 
Von dem Aufruf `farmingObject[3]["price"]` würde ich dir jedoch abraten, da sich die Reihenfolge der Liste _in der Theorie_ jederzeit ändern kann (Beispielsweise bei neuen Farmingrouten).

Trotzdem hier ein paar kleine Anregungen für Funktionen, die dir das arbeiten an einer Liste vereinfachen können:
- Wenn du eine Liste von allen Farmingpreisen ausgeben möchtest, kannst du dies einfach mit einer for-Schleife umsetzen:
```php
foreach ($farmingItems as $farmingItem) {
  echo $farmingItem["itemName"] . " hat aktuell einen Preis von " . $farmingItem["price"];
}
```
- Wenn du, wie in deinem Beispiel, nur den Preis von Mehl haben möchtest kann dir so eine Funktion hier bestimmt helfen:
```php
function getFarmingPrice($farmingPrices, $itemName) {
  foreach ($farmingPrices as $entry) {
    if ($entry["itemName"] == $itemName) {
      return $entry["price"];
    }
  }
  
  return 0;
}

$mehl = getFarmingPrice($array, "Mehl");
```

**Comment by Distel04** [comment]
Stimmt, dass ist eine gute Idee.

Danke die
