### ISSUE TITLE
Valid-Request strange API behaviour

### ISSUE THREAD

**Issue by Demonofpower** [Hyperjo/Dokumentation#5]
In the documentation:
Request: https://api.hyperjo.de/?version=1&request=valid&key=978ba661-9ea9-430b-b2e1-38930d735fd9&characterId=421

Expected result: {"valid":false} or {"characterId": 421,"valid":true}

Result: {}

**Comment by Demonofpower** [comment]
After some more investigation:
You can give any valid GUID as input and the result will be {} but if you deliver an invalid GUID  like "123-123-1" you get {"valid":false} as expected

**Comment by Markus1812** [comment]
Thanks for the report. If you now provide a valid key (uuidv4) with the corresponding characterId (XXXX) the result is `{"characterId": 421,"valid":true}` as expected.
