### ISSUE TITLE
Derzeitiger "Preistyp" in Farming API

### ISSUE THREAD

**Issue by Demonofpower** [Hyperjo/Dokumentation#8]
Es wäre schön wenn die Information der Faminggegenstände mitgeliefert wird in welchem Bereich sich der Preis befindet.
Grün = Zu wenig Interesse
Grau = Normal
Rot = Zu viel Interesse

**Comment by Markus1812** [comment]
Ist als `demand` Attribut eingefügt. Anstatt Farben ist der Wert einfach negativ, 0 oder positiv, so kann jeder seine Farben selbst wählen :)
